version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  todo:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env.local

volumes:
  pgdata:
